---
functional:
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Сайт должен быть адаптирован для слабовидящих людей
  - Сайт должен обрабатывать ошибки в случае сбоя соединения
  - Сайт должен соответововать законодательным требованиям онлайн-продаж
  - После оформления покупки пользователь указывает номер телефона
  - В корзине должно быть указано название товара, количество, сумма до скидки, сумма после скидки, кнопка удаления
  - В корзине должна быть возможность менять количество товара
